/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelBeans.BeansCliente;
import ModelBeans.ModeloTabela;
import ModelConexao.ConexaoBD;
import ModelDao.DaoCliente;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Aurelio Macie Junior
 */
public class CadastroCliente extends javax.swing.JFrame {
    
        BeansCliente cliente = new BeansCliente();
        ModelDao.DaoCliente control = new DaoCliente();
        ConexaoBD conex = new ConexaoBD();
        int flag = 0;
        
   
    public CadastroCliente() {
        initComponents();
        conex.conexao();
        preencherTabela("select * from clientes order by id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldContactoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodigoCliente = new javax.swing.JTextField();
        jButtonNovoCliente = new javax.swing.JButton();
        jButtonSalvarCliente = new javax.swing.JButton();
        jButtonCancelarCliente = new javax.swing.JButton();
        jButtonEditarCliente = new javax.swing.JButton();
        jButtonExcluirCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextFieldPesquisaCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSexoCliente = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMoradaCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldIdadeCliente = new javax.swing.JTextField();
        jButtonSairCliente = new javax.swing.JButton();
        jButtonPesquisaCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 95, 50, 29);

        jTextFieldNomeCliente.setEnabled(false);
        getContentPane().add(jTextFieldNomeCliente);
        jTextFieldNomeCliente.setBounds(74, 95, 242, 29);

        jLabel2.setText("Contacto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 142, 60, 34);

        jTextFieldContactoCliente.setEnabled(false);
        getContentPane().add(jTextFieldContactoCliente);
        jTextFieldContactoCliente.setBounds(74, 146, 242, 27);

        jLabel3.setText("CADASTRO DE CLIENTE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(121, 11, 520, 25);

        jLabel4.setText("Codigo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 51, 60, 38);

        jTextFieldCodigoCliente.setEnabled(false);
        jTextFieldCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodigoCliente);
        jTextFieldCodigoCliente.setBounds(74, 56, 75, 29);

        jButtonNovoCliente.setText("Novo");
        jButtonNovoCliente.setToolTipText("Criar Novo Cliente");
        jButtonNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovoCliente);
        jButtonNovoCliente.setBounds(548, 13, 90, 23);

        jButtonSalvarCliente.setText("Salvar");
        jButtonSalvarCliente.setToolTipText("Salvar Dados Do Cliente");
        jButtonSalvarCliente.setEnabled(false);
        jButtonSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvarCliente);
        jButtonSalvarCliente.setBounds(548, 42, 90, 23);

        jButtonCancelarCliente.setText("Cancelar");
        jButtonCancelarCliente.setToolTipText("Cancelar Cadastro");
        jButtonCancelarCliente.setEnabled(false);
        jButtonCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarCliente);
        jButtonCancelarCliente.setBounds(548, 76, 90, 23);

        jButtonEditarCliente.setText("Editar");
        jButtonEditarCliente.setToolTipText("Corrigir Dados Do Cliente");
        jButtonEditarCliente.setEnabled(false);
        jButtonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarCliente);
        jButtonEditarCliente.setBounds(548, 105, 90, 23);

        jButtonExcluirCliente.setText("Excluir");
        jButtonExcluirCliente.setToolTipText("Eliminar Cliente");
        jButtonExcluirCliente.setEnabled(false);
        jButtonExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirCliente);
        jButtonExcluirCliente.setBounds(548, 134, 90, 23);

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCliente.setToolTipText("Tabela De Dados");
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 228, 710, 170);

        jTextFieldPesquisaCliente.setToolTipText("Pesquisas");
        jTextFieldPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisaCliente);
        jTextFieldPesquisaCliente.setBounds(460, 50, 47, 29);

        jLabel6.setText("Sexo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(334, 95, 35, 29);

        jComboBoxSexoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jComboBoxSexoCliente.setEnabled(false);
        jComboBoxSexoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxSexoCliente);
        jComboBoxSexoCliente.setBounds(373, 99, 71, 20);

        jLabel7.setText("Morada");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 180, 50, 30);

        jTextFieldMoradaCliente.setEnabled(false);
        jTextFieldMoradaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMoradaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMoradaCliente);
        jTextFieldMoradaCliente.setBounds(380, 180, 170, 30);

        jLabel8.setText("Idade");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 184, 50, 30);

        jTextFieldIdadeCliente.setEnabled(false);
        getContentPane().add(jTextFieldIdadeCliente);
        jTextFieldIdadeCliente.setBounds(70, 180, 240, 30);

        jButtonSairCliente.setText("X");
        jButtonSairCliente.setToolTipText("Encerar Cadastro");
        jButtonSairCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairCliente);
        jButtonSairCliente.setBounds(670, 0, 40, 23);

        jButtonPesquisaCliente.setText("Pesquisa");
        jButtonPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaClienteActionPerformed(evt);
            }
        });
        jButtonPesquisaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonPesquisaClienteKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonPesquisaCliente);
        jButtonPesquisaCliente.setBounds(340, 50, 110, 30);

        setSize(new java.awt.Dimension(726, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoClienteActionPerformed

    private void jTextFieldMoradaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMoradaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMoradaClienteActionPerformed

    private void jButtonSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarClienteActionPerformed
   
        jTextFieldPesquisaCliente.setText("");
        if (jTextFieldNomeCliente.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO 'NOME' PARA CONTINUAR!");
           jTextFieldNomeCliente.requestFocus();
       }else if(jTextFieldContactoCliente.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO 'CONTACTO' PARA CONTINUAR!");
           jTextFieldContactoCliente.requestFocus();
       }else if(jTextFieldIdadeCliente.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO 'IDADE' PARA CONTINUAR!");
           jTextFieldIdadeCliente.requestFocus();   
           }else if(jTextFieldMoradaCliente.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO 'MORADA' PARA CONTINUAR!");
           jTextFieldMoradaCliente.requestFocus(); 
           
           } else
           
        if (flag==1){
            
        cliente.setNome(jTextFieldNomeCliente.getText());
        cliente.setContacto(jTextFieldContactoCliente.getText());
        cliente.setIdade(Integer.parseInt(jTextFieldIdadeCliente.getText()));
        cliente.setSexo((String)jComboBoxSexoCliente.getSelectedItem());
        cliente.setMorada(jTextFieldMoradaCliente.getText());
        control.salvar(cliente);
        
        
        jTextFieldCodigoCliente.setText("");
        jTextFieldContactoCliente.setText("");
        jTextFieldIdadeCliente.setText("");
        jTextFieldMoradaCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jTextFieldPesquisaCliente.setText("");
        
        jButtonEditarCliente.setEnabled(false);
        jButtonCancelarCliente.setEnabled(false);
        jButtonSalvarCliente.setEnabled(false);
        
        jTextFieldCodigoCliente.setEnabled(false);
        jTextFieldContactoCliente.setEnabled(false);
        jTextFieldIdadeCliente.setEnabled(false);
        jTextFieldMoradaCliente.setEnabled(false);
        jTextFieldNomeCliente.setEnabled(false);
        jTextFieldPesquisaCliente.setEnabled(true);
        jComboBoxSexoCliente.setEnabled(false);
        
        preencherTabela("select * from clientes order by id");
        
        }else{
            
            cliente.setCodigo(Integer.parseInt(jTextFieldCodigoCliente.getText()));
            cliente.setContacto(jTextFieldContactoCliente.getText());
            cliente.setIdade(Integer.parseInt(jTextFieldIdadeCliente.getText()));
            cliente.setMorada(jTextFieldMoradaCliente.getText());
            cliente.setNome(jTextFieldNomeCliente.getText());
            cliente.setSexo((String)jComboBoxSexoCliente.getSelectedItem());
            control.editar(cliente);
            
            
                jButtonSalvarCliente.setEnabled(false);
                
                jTextFieldCodigoCliente.setEnabled(false);
                jTextFieldContactoCliente.setEnabled(false);
                jTextFieldIdadeCliente.setEnabled(false);
                jTextFieldMoradaCliente.setEnabled(false);
                jTextFieldNomeCliente.setEnabled(false);
                jTextFieldPesquisaCliente.setEnabled(true);
                jComboBoxSexoCliente.setEnabled(false);
                preencherTabela("select * from clientes order by id");
       }
    }//GEN-LAST:event_jButtonSalvarClienteActionPerformed

    private void jButtonSairClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairClienteActionPerformed
        conex.desconexao();
        System.exit(0);
    }//GEN-LAST:event_jButtonSairClienteActionPerformed

    private void jButtonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoClienteActionPerformed
        flag = 1;
        
        jTextFieldPesquisaCliente.setText("");
        jTextFieldCodigoCliente.setText("");
        jTextFieldContactoCliente.setText("");
        jTextFieldIdadeCliente.setText("");
        jTextFieldMoradaCliente.setText("");
        jTextFieldNomeCliente.setText("");
        
        jButtonCancelarCliente.setEnabled(true);
        jButtonEditarCliente.setEnabled(false);
        jButtonExcluirCliente.setEnabled(false);
        jButtonSalvarCliente.setEnabled(true);
        jTextFieldCodigoCliente.setEnabled(false);
        jTextFieldContactoCliente.setEnabled(true);
        jTextFieldIdadeCliente.setEnabled(true);
        jTextFieldMoradaCliente.setEnabled(true);
        jTextFieldNomeCliente.setEnabled(true);
        jTextFieldPesquisaCliente.setEnabled(true);
        jComboBoxSexoCliente.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoClienteActionPerformed

    private void jButtonPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaClienteActionPerformed
       
        cliente.setPesquisa(jTextFieldPesquisaCliente.getText());
        BeansCliente model = control.buscaCliente(cliente);
        
        jTextFieldPesquisaCliente.setText("");
        jTextFieldPesquisaCliente.setEnabled(true);
        jTextFieldCodigoCliente.setEnabled(false);
        jTextFieldNomeCliente.setEnabled(false);
        jTextFieldContactoCliente.setEnabled(false);
        jTextFieldIdadeCliente.setEnabled(false);
        jComboBoxSexoCliente.setEnabled(false);
        jTextFieldMoradaCliente.setEnabled(false);
        jButtonSalvarCliente.setEnabled(false);
        jButtonCancelarCliente.setEnabled(false);
        jButtonNovoCliente.setEnabled(true);
        jButtonEditarCliente.setEnabled(true);
        jButtonExcluirCliente.setEnabled(true);
        
        jTextFieldCodigoCliente.setText(String.valueOf(model.getCodigo()));
        jTextFieldNomeCliente.setText(model.getNome());
        jTextFieldContactoCliente.setText(model.getContacto());
        jTextFieldIdadeCliente.setText(String.valueOf(model.getIdade()));
        jComboBoxSexoCliente.setSelectedItem(model.getSexo());
        jTextFieldMoradaCliente.setText(model.getMorada());
        preencherTabela("select * from clientes where nome like '%" + cliente.getPesquisa() + "%'");
    }//GEN-LAST:event_jButtonPesquisaClienteActionPerformed

    private void jButtonCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarClienteActionPerformed
        jTextFieldPesquisaCliente.setText("");
        jButtonCancelarCliente.setEnabled(true);
        jButtonEditarCliente.setEnabled(false);
        jButtonExcluirCliente.setEnabled(false);
        jButtonCancelarCliente.setEnabled(!true);
        jButtonSalvarCliente.setEnabled(!true);
        jButtonNovoCliente.setEnabled(true);
        jTextFieldCodigoCliente.setEnabled(!true);
        jTextFieldContactoCliente.setEnabled(!true);
        jTextFieldIdadeCliente.setEnabled(!true);
        jTextFieldMoradaCliente.setEnabled(!true);
        jTextFieldNomeCliente.setEnabled(!true);
        jTextFieldPesquisaCliente.setEnabled(true);
        jComboBoxSexoCliente.setEnabled(!true); 
        
        jTextFieldCodigoCliente.setText("");
        
    }//GEN-LAST:event_jButtonCancelarClienteActionPerformed

    private void jButtonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarClienteActionPerformed
        flag = 2;
        jTextFieldPesquisaCliente.setText("");
        jButtonSalvarCliente.setEnabled(true);
        jButtonCancelarCliente.setEnabled(true);
        jButtonEditarCliente.setEnabled(false);
        jButtonNovoCliente.setEnabled(false);
        jButtonExcluirCliente.setEnabled(false);
        jTextFieldCodigoCliente.setEnabled(false);
        jTextFieldContactoCliente.setEnabled(true);
        jTextFieldIdadeCliente.setEnabled(true);
        jTextFieldMoradaCliente.setEnabled(true);
        jTextFieldNomeCliente.setEnabled(true);
        jTextFieldPesquisaCliente.setEnabled(true);
        jComboBoxSexoCliente.setEnabled(true);
        preencherTabela("select * from clientes order by id");
    }//GEN-LAST:event_jButtonEditarClienteActionPerformed

    private void jComboBoxSexoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexoClienteActionPerformed

    }//GEN-LAST:event_jComboBoxSexoClienteActionPerformed

    private void jButtonExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirClienteActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "QUER MESMO EXCLUIR?");
            if(resposta == JOptionPane.YES_OPTION){
                cliente.setCodigo(Integer.parseInt(jTextFieldCodigoCliente.getText()));
                control.excluir(cliente);
                
                jTextFieldPesquisaCliente.setText("");
                jTextFieldCodigoCliente.setText("");
                jTextFieldContactoCliente.setText("");
                jTextFieldIdadeCliente.setText("");
                jTextFieldMoradaCliente.setText("");
                jTextFieldNomeCliente.setText("");
                jButtonEditarCliente.setEnabled(false);
                jButtonExcluirCliente.setEnabled(false);
                preencherTabela("select * from clientes order by id");
            }
    }//GEN-LAST:event_jButtonExcluirClienteActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        String nome = ""+jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select * from clientes where nome='"+nome+"'");
            try {
                conex.rs.first();
                jTextFieldCodigoCliente.setText(String.valueOf(conex.rs.getInt("id")));
                jTextFieldNomeCliente.setText(conex.rs.getString("nome"));
                jTextFieldContactoCliente.setText(conex.rs.getString("contacto"));
                jTextFieldIdadeCliente.setText(String.valueOf(conex.rs.getInt("idade")));
                jComboBoxSexoCliente.setSelectedItem(String.valueOf(conex.rs.getString("sexo")));
                jTextFieldMoradaCliente.setText(conex.rs.getString("morada"));
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERRO NA CAPTURA DE DADOS!\n ERROR: "+ex);
            }
        
        conex.desconexao();
        jButtonEditarCliente.setEnabled(true);
        jButtonExcluirCliente.setEnabled(true);
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jTextFieldPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaClienteActionPerformed

    private void jButtonPesquisaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonPesquisaClienteKeyPressed

    }//GEN-LAST:event_jButtonPesquisaClienteKeyPressed
    
    
    public void preencherTabela(String sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"id", "nome", "contacto", "idade", "sexo", "morada"};
        conex.conexao();
        
        conex.executaSql(sql);
            try {
                conex.rs.first();
                do{
                  dados.add(new Object[]{conex.rs.getInt("id"),conex.rs.getString("nome"),conex.rs.getString("contacto"),conex.rs.getInt("idade"),conex.rs.getString("sexo"),conex.rs.getString("morada")});
                }while(conex.rs.next());
            } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "REALIZE NOVAMENTE A BUSCA!");
            }
            
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTableCliente.setModel(modelo);
        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableCliente.getColumnModel().getColumn(0).setResizable(false);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(170);
        jTableCliente.getColumnModel().getColumn(1).setResizable(false);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(170);
        jTableCliente.getColumnModel().getColumn(2).setResizable(false);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTableCliente.getColumnModel().getColumn(3).setResizable(false);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(70);
        jTableCliente.getColumnModel().getColumn(4).setResizable(false);
        jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(170);
        jTableCliente.getColumnModel().getColumn(5).setResizable(false);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);
        jTableCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconexao();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarCliente;
    private javax.swing.JButton jButtonEditarCliente;
    private javax.swing.JButton jButtonExcluirCliente;
    private javax.swing.JButton jButtonNovoCliente;
    private javax.swing.JButton jButtonPesquisaCliente;
    private javax.swing.JButton jButtonSairCliente;
    private javax.swing.JButton jButtonSalvarCliente;
    private javax.swing.JComboBox<String> jComboBoxSexoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldCodigoCliente;
    private javax.swing.JTextField jTextFieldContactoCliente;
    private javax.swing.JTextField jTextFieldIdadeCliente;
    private javax.swing.JTextField jTextFieldMoradaCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldPesquisaCliente;
    // End of variables declaration//GEN-END:variables
}
